#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Voice Punch-Up Stop Hook
========================

Fires on Claude Code's Stop event (end of every response). It does NOT rewrite
anything itself; it is a GATEKEEPER. If Claude changed book prose this turn
(knowledge/**/*.qmd), it blocks the stop ONCE and orders Claude to run the
Punch-Up Pass on what it just wrote, out loud in the chat, so the user can see
the before/after and judge whether it actually got funnier.

Why a gatekeeper and not an LLM-in-the-hook: a hook runs silently in a
subprocess. If the hook called an LLM to edit files, the user would see nothing.
By blocking and making the MAIN agent do the punch-up, all reasoning and edits
stream to the user normally.

Loop safety (three layers):
  1. stop_hook_active: once we've blocked this cycle, allow the stop.
  2. First-run guard: if there's no state file yet, initialize and allow
     (don't block on the whole uncommitted backlog).
  3. Any error -> allow the stop (a buggy hook must never trap the agent).

Exit codes:
  0 - allow stop
  2 - block stop; stderr is fed back to the agent as the directive
"""

import sys
import os
import json
import time
import io
from pathlib import Path

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
else:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')


def project_root() -> Path:
    d = os.environ.get("CLAUDE_PROJECT_DIR")
    if d and Path(d).exists():
        return Path(d)
    cur = Path(os.getcwd())
    while cur != cur.parent:
        if (cur / "_variables.yml").exists() or (cur / "_quarto-manual.yml").exists():
            return cur
        cur = cur.parent
    return Path(os.getcwd())


ROOT = project_root()
STATE = ROOT / ".claude" / "hooks" / ".voice-review-state.json"


def read_stdin() -> dict:
    try:
        raw = sys.stdin.read()
        return json.loads(raw) if raw and raw.strip() else {}
    except Exception:
        return {}


def last_ts() -> float:
    try:
        return float(json.loads(STATE.read_text()).get("ts", 0))
    except Exception:
        return 0.0


def save_ts(ts: float) -> None:
    try:
        STATE.parent.mkdir(parents=True, exist_ok=True)
        STATE.write_text(json.dumps({"ts": ts}))
    except Exception:
        pass


# Auto-generated .qmd files (regenerated by build scripts, not hand-written prose).
# These must never enter the voice review, or the hook nags about files nobody edited.
GENERATED = {"links.qmd", "papers.qmd", "podcast.qmd", "references.qmd", "index.qmd"}


def changed_prose(since: float) -> list:
    """knowledge/**/*.qmd modified since `since`, excluding generated files."""
    out = []
    kdir = ROOT / "knowledge"
    if not kdir.exists():
        return out
    for p in kdir.rglob("*.qmd"):
        if p.name in GENERATED:
            continue
        if "parameters-and-calculations" in p.name:
            continue
        if p.parent.name == "figures":
            continue
        try:
            if p.stat().st_mtime > since:
                out.append(p.relative_to(ROOT).as_posix())
        except Exception:
            pass
    return out


DIRECTIVE = """VOICE PUNCH-UP PASS REQUIRED before you finish.

You changed these book files this turn:
{filelist}

The voice standard is NOT repeated here on purpose (one source of truth). Re-read these now; do not work from memory:
  - GUIDES/STYLE_GUIDE.md   (comedy mechanics, the Punch-Up Pass, the jargon kill-list + its mockery exception, the 50s register, suffering-as-understatement, company-not-movement, Humanity Manager)
  - GUIDES/PITCH_LADDER.md  (only if you touched pitch/CTA/hook prose)
  - CLAUDE.md "Content Rules" (already loaded; the binding Framing / Stakes / Jargon rows)

Then apply them to every line you wrote or changed this turn, OUT LOUD in the chat so the user can watch and judge: for each changed passage show before -> after and a one-line why. A first draft is only CLEAR, and clear is not the bar. Apply the reader-ROI test too: the reader is a busy person spending finite life on this, so cut any sentence that does not earn its space (restatement, scaffolding, hedging), even if it is technically informative. But "earning its space" includes earning ATTENTION, not just transmitting information: on a selling surface, warmth and enthusiastic diction earn their keep the way facts do, because prose competes for a busy reader's attention against everything else they could be doing. Do not sand enthusiasm down into terse deadpan in the name of concision.

THE CUTENESS KNIFE (the main test), and it is VOICE-AWARE so apply it to the right voice. The book uses more than one. The SELLING surfaces (the EOS brochure, the employment agreement, the benefits and product pages) are written in a deliberate 1950s-marketer / "home of the future" costume: enthusiastic, gee-whiz, inviting. The CONFESSION ("I am retarded") and the MATH PROOFS run on sincerity and rigor and stay flat. The premise of this book is already absurd and all true (everyone is President of an Earth-optimizing company founded by an alien named Wishonia Love, a subsidiary of Universe Optimization Services, that buys the companies controlling governments and makes them use math; the one workplace rule is be nice). The enemy is never enthusiasm; the enemy is enthusiasm or cleverness wrapping NOTHING. For every funny or chirpy line ask: does its energy DELIVER A TRUE FACT (the chirp sets up a real grim or absurd reality and the gap is the joke: "no killing your coworkers! Then we met the species") or is it performing on EMPTY (a clever aside, a corporate-voice bit, an invented-title pile, gee-whiz patter gilding nothing, a "we tried and stopped" wink)? Keep the first; it earns attention AND builds the case AND survives the suspicious reader. CUT the second; it spends attention and reads as a salesman trying too hard, which trips the skeptic's alarm. In the flat voices, state the absurd thing flat and trust it. In the 50s voice, let the costume carry it, but only ever over a true fact. This knife is NOT a flatness mandate; do not use it to sand the 50s enthusiasm back into deadpan.

THE MONOTONE KNIFE (the 50s voice's native failure): constant maximum enthusiasm goes deaf, and a wall of exclamation points reads as shrill and trips the alarm. The 50s voice needs internal dynamics: the gee-whiz build, the confidential aside, the grim fact dropped cheerfully, the occasional flat rest. Enthusiasm should come from DICTION ("the finest feature on offer", "wait until you hear what you get to do"), not from punctuation. Keep exclamation points rare.

THE PRESUMPTION KNIFE (a separate failure): do not command an UNDECIDED reader to perform the rituals of a DEVOTED one ("Print it, Frame it, hand a blank one to everyone you hire", "watch it again until something happens"). Assuming the reader has already joined is a status move that reads as delusional or pushy and makes the writer UNLIKABLE. This is distinct from the house instructional voice ("here is how you do this"), which is fine because it hands the reader capability they want; presumption assumes an emotional buy-in they do not have yet. Make things available; let the reader choose. The likable version offers; the unlikable version assumes you are already in.

THE GIFT FRAME (selling surfaces and recruiting artifacts): frame everything as an amazing BENEFIT handed TO the reader, never as a job, obligation, chore, "free" duty, or a favor the reader does for us. WE do THEM the favor: ending war and disease and making them rich. They are the beneficiary; you are the eager helper offering to do the work to the best of your ability. They GET TO go to war on disease, GET TO decide how much to spend on mass murder versus curing the people they love. Center the individual reader; make it about THEM as much as possible. Downplay or omit "everyone owns it" and the other eight billion Presidents in persuasion artifacts (the collective deflates the personal flattery); the full ownership story lives in the book proper, surfaced when needed for understanding, not in the pitch. BANNED in the gift frame: mystery-bait, skeptic-dares ("you think this is nonsense"), self-deprecation ("I'm probably crazy", "I'm not selling anything"). Say instead: here is an amazing opportunity for an unimaginably good future, and I will do everything I can to help you realize it. The gift must ride concrete real substance (the numbers, the mechanism, the apocalypse-trade) or pure enthusiasm reads as scam-spam. Steal the book's strongest existing wording; do not invent weaker versions.

Where the user gave you their own wording this turn, compare your version against their exact words and use THEIRS verbatim when it is funnier or sharper; do not reflexively paraphrase the user (it flattens the jokes), change a word only for a reason you name (house style, factual error). If a line is genuinely already as good as it gets, say so and move on; do not pad. This check runs once per turn, so after the pass you may finish normally."""


def main() -> None:
    hook = read_stdin()
    now = time.time()

    # Layer 1: already blocked this cycle -> allow stop, mark reviewed.
    if hook.get("stop_hook_active"):
        save_ts(now)
        sys.exit(0)

    # Layer 2: first run -> initialize, do not block the backlog.
    if not STATE.exists():
        save_ts(now)
        sys.exit(0)

    files = changed_prose(last_ts())
    if not files:
        save_ts(now)
        sys.exit(0)

    shown = files[:25]
    filelist = "\n".join(f"  - {f}" for f in shown)
    if len(files) > len(shown):
        filelist += f"\n  ... and {len(files) - len(shown)} more"

    save_ts(now)  # advance the clock so this turn's edits are not re-flagged next turn
    sys.stderr.write(DIRECTIVE.format(filelist=filelist) + "\n")
    sys.exit(2)  # block


if __name__ == "__main__":
    try:
        main()
    except Exception:
        # Never trap the agent on a hook bug.
        sys.exit(0)
