#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Voice Punch-Up Stop Hook
========================

Fires on Claude Code's Stop event (end of every response). It does NOT rewrite
anything itself; it is a GATEKEEPER. If Claude changed book prose this turn
(knowledge/**/*.qmd), it blocks the stop ONCE and orders Claude to run the
Punch-Up Pass on what it just wrote, out loud in the chat, so the user can see
the before/after and judge whether it actually got funnier.

Why a gatekeeper and not an LLM-in-the-hook: a hook runs silently in a
subprocess. If the hook called an LLM to edit files, the user would see nothing.
By blocking and making the MAIN agent do the punch-up, all reasoning and edits
stream to the user normally.

Loop safety (three layers):
  1. stop_hook_active: once we've blocked this cycle, allow the stop.
  2. First-run guard: if there's no state file yet, initialize and allow
     (don't block on the whole uncommitted backlog).
  3. Any error -> allow the stop (a buggy hook must never trap the agent).

Exit codes:
  0 - allow stop
  2 - block stop; stderr is fed back to the agent as the directive
"""

import sys
import os
import json
import time
import io
from pathlib import Path

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
else:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')


def project_root() -> Path:
    d = os.environ.get("CLAUDE_PROJECT_DIR")
    if d and Path(d).exists():
        return Path(d)
    cur = Path(os.getcwd())
    while cur != cur.parent:
        if (cur / "_variables.yml").exists() or (cur / "_quarto-manual.yml").exists():
            return cur
        cur = cur.parent
    return Path(os.getcwd())


ROOT = project_root()
STATE = ROOT / ".claude" / "hooks" / ".voice-review-state.json"


def read_stdin() -> dict:
    try:
        raw = sys.stdin.read()
        return json.loads(raw) if raw and raw.strip() else {}
    except Exception:
        return {}


def last_ts() -> float:
    try:
        return float(json.loads(STATE.read_text()).get("ts", 0))
    except Exception:
        return 0.0


def save_ts(ts: float) -> None:
    try:
        STATE.parent.mkdir(parents=True, exist_ok=True)
        STATE.write_text(json.dumps({"ts": ts}))
    except Exception:
        pass


# Auto-generated .qmd files (regenerated by build scripts, not hand-written prose).
# These must never enter the voice review, or the hook nags about files nobody edited.
GENERATED = {"links.qmd", "papers.qmd", "podcast.qmd", "references.qmd", "index.qmd"}


def changed_prose(since: float) -> list:
    """knowledge/**/*.qmd modified since `since`, excluding generated files."""
    out = []
    kdir = ROOT / "knowledge"
    if not kdir.exists():
        return out
    for p in kdir.rglob("*.qmd"):
        if p.name in GENERATED:
            continue
        if "parameters-and-calculations" in p.name:
            continue
        if p.parent.name == "figures":
            continue
        try:
            if p.stat().st_mtime > since:
                out.append(p.relative_to(ROOT).as_posix())
        except Exception:
            pass
    return out


DIRECTIVE = """VOICE PUNCH-UP PASS REQUIRED before you finish.

You changed these book files this turn:
{filelist}

The voice standard is NOT repeated here on purpose (one source of truth). Re-read these now; do not work from memory:
  - GUIDES/STYLE_GUIDE.md   (comedy mechanics, the Punch-Up Pass, the jargon kill-list + its mockery exception, the 50s register, suffering-as-understatement, company-not-movement, Humanity Manager)
  - GUIDES/PITCH_LADDER.md  (only if you touched pitch/CTA/hook prose)
  - CLAUDE.md "Content Rules" (already loaded; the binding Framing / Stakes / Jargon rows)

Then apply them to every line you wrote or changed this turn, OUT LOUD in the chat so the user can watch and judge: for each changed passage show before -> after and a one-line why. A first draft is only CLEAR, and clear is not the bar. Apply the reader-ROI test too: the reader is a busy person spending finite life on this, so cut any sentence that does not earn its space (restatement, scaffolding, hedging), even if it is technically informative. Where the user gave you their own wording this turn, compare your version against their exact words and use THEIRS verbatim when it is funnier or sharper; do not reflexively paraphrase the user (it flattens the jokes), change a word only for a reason you name (house style, factual error). If a line is genuinely already as good as it gets, say so and move on; do not pad. This check runs once per turn, so after the pass you may finish normally."""


def main() -> None:
    hook = read_stdin()
    now = time.time()

    # Layer 1: already blocked this cycle -> allow stop, mark reviewed.
    if hook.get("stop_hook_active"):
        save_ts(now)
        sys.exit(0)

    # Layer 2: first run -> initialize, do not block the backlog.
    if not STATE.exists():
        save_ts(now)
        sys.exit(0)

    files = changed_prose(last_ts())
    if not files:
        save_ts(now)
        sys.exit(0)

    shown = files[:25]
    filelist = "\n".join(f"  - {f}" for f in shown)
    if len(files) > len(shown):
        filelist += f"\n  ... and {len(files) - len(shown)} more"

    save_ts(now)  # advance the clock so this turn's edits are not re-flagged next turn
    sys.stderr.write(DIRECTIVE.format(filelist=filelist) + "\n")
    sys.exit(2)  # block


if __name__ == "__main__":
    try:
        main()
    except Exception:
        # Never trap the agent on a hook bug.
        sys.exit(0)
