#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Voice Punch-Up Stop Hook
========================

Fires on Claude Code's Stop event (end of every response). It does NOT rewrite
anything itself; it is a GATEKEEPER. If Claude changed book prose this turn
(knowledge/**/*.qmd), it blocks the stop ONCE and orders Claude to run the
Punch-Up Pass on what it just wrote, out loud in the chat, so the user can see
the before/after and judge whether it actually got funnier.

Why a gatekeeper and not an LLM-in-the-hook: a hook runs silently in a
subprocess. If the hook called an LLM to edit files, the user would see nothing.
By blocking and making the MAIN agent do the punch-up, all reasoning and edits
stream to the user normally.

Loop safety (three layers):
  1. stop_hook_active: once we've blocked this cycle, allow the stop.
  2. First-run guard: if there's no state file yet, initialize and allow
     (don't block on the whole uncommitted backlog).
  3. Any error -> allow the stop (a buggy hook must never trap the agent).

Exit codes:
  0 - allow stop
  2 - block stop; stderr is fed back to the agent as the directive
"""

import sys
import os
import json
import time
import io
import subprocess
from pathlib import Path

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
else:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')


def project_root() -> Path:
    d = os.environ.get("CLAUDE_PROJECT_DIR")
    if d and Path(d).exists():
        return Path(d)
    cur = Path(os.getcwd())
    while cur != cur.parent:
        if (cur / "_variables.yml").exists() or (cur / "_quarto-manual.yml").exists():
            return cur
        cur = cur.parent
    return Path(os.getcwd())


ROOT = project_root()
STATE = ROOT / ".claude" / "hooks" / ".voice-review-state.json"


def read_stdin() -> dict:
    try:
        raw = sys.stdin.read()
        return json.loads(raw) if raw and raw.strip() else {}
    except Exception:
        return {}


def last_ts() -> float:
    try:
        return float(json.loads(STATE.read_text()).get("ts", 0))
    except Exception:
        return 0.0


def save_ts(ts: float) -> None:
    try:
        STATE.parent.mkdir(parents=True, exist_ok=True)
        STATE.write_text(json.dumps({"ts": ts}))
    except Exception:
        pass


# Auto-generated .qmd files (regenerated by build scripts, not hand-written prose).
# These must never enter the voice review, or the hook nags about files nobody edited.
GENERATED = {"links.qmd", "papers.qmd", "podcast.qmd", "references.qmd", "index.qmd"}


def changed_prose(since: float) -> list:
    """knowledge/**/*.qmd modified since `since`, excluding generated files."""
    out = []
    kdir = ROOT / "knowledge"
    if not kdir.exists():
        return out
    for p in kdir.rglob("*.qmd"):
        if p.name in GENERATED:
            continue
        if "parameters-and-calculations" in p.name:
            continue
        if p.parent.name == "figures":
            continue
        try:
            if p.stat().st_mtime > since:
                out.append(p.relative_to(ROOT).as_posix())
        except Exception:
            pass
    return out


def scan_hits(files: list) -> str:
    """Run the deterministic banned-phrase linter (scripts/voice-check.py) on the
    changed files and return its combined output. This is the mechanical net under
    the spots judgment keeps missing ('same trade', 'defense', 'proxy campaign'):
    the punch-up pass catches novel cute/salesy lines, the scanner catches the exact
    repeat offenders the style guide bans."""
    checker = ROOT / "scripts" / "voice-check.py"
    if not checker.exists() or not files:
        return ""
    out = []
    for f in files:
        try:
            r = subprocess.run(
                [sys.executable, str(checker), str(ROOT / f)],
                capture_output=True, text=True, timeout=15,
            )
            if r.returncode != 0 and r.stdout.strip():
                out.append(r.stdout.rstrip())
        except Exception:
            pass
    return "\n".join(out)


DIRECTIVE = """VOICE PUNCH-UP PASS REQUIRED before you finish.

You changed these book files this turn:
{filelist}

Re-read GUIDES/STYLE_GUIDE.md now; do not work from memory. It is the single source of truth for the voice: the Voice Map (which surface gets which voice), the comedy mechanics and kill-tests, the Punch-Up Pass discipline (tie goes to the incumbent; no rule-zealotry; keep the author's exact words), the gift frame, offer-don't-presume, and asker-not-asked. Also read GUIDES/VOICE_RUBRIC.md (the 11 edit patterns mined from 34,742 of the author's real edits) and pull relevant pairs from scripts/voice/voice-exemplars.jsonl; for any passage you can run `python scripts/voice/voice-critic.py <file>` to get a critique in his voice. CLAUDE.md's Content Rules also bind. If you touched pitch/CTA prose, re-read GUIDES/PITCH_LADDER.md too.

Then, OUT LOUD in the chat so the user can judge: for each passage you changed, show before -> after and a one-line why, applying the guide's kill-tests. A first draft is only CLEAR, and clear is not the bar; but do not sand warmth into terse deadpan in the name of concision either. If a line is already as good as it gets, say so and move on; do not pad. If your changes this turn were mechanical (links, renames, parameter swaps), say so in one line and finish. This check runs once per turn, so after the pass you may finish normally."""


def main() -> None:
    hook = read_stdin()
    now = time.time()

    # Layer 1: already blocked this cycle -> allow stop, mark reviewed.
    if hook.get("stop_hook_active"):
        save_ts(now)
        sys.exit(0)

    # Layer 2: first run -> initialize, do not block the backlog.
    if not STATE.exists():
        save_ts(now)
        sys.exit(0)

    files = changed_prose(last_ts())
    if not files:
        save_ts(now)
        sys.exit(0)

    shown = files[:25]
    filelist = "\n".join(f"  - {f}" for f in shown)
    if len(files) > len(shown):
        filelist += f"\n  ... and {len(files) - len(shown)} more"

    directive = DIRECTIVE.format(filelist=filelist)
    hits = scan_hits(files)
    if hits:
        directive += (
            "\n\nThe deterministic voice-check scanner (scripts/voice-check.py) also "
            "flagged these exact phrases, which the STYLE_GUIDE bans. Fix each one, or "
            "justify the keep (a buzzword survives only when you are quoting it to mock "
            "it):\n\n" + hits
        )

    save_ts(now)  # advance the clock so this turn's edits are not re-flagged next turn
    sys.stderr.write(directive + "\n")
    sys.exit(2)  # block


if __name__ == "__main__":
    try:
        main()
    except Exception:
        # Never trap the agent on a hook bug.
        sys.exit(0)
