'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function VictoryBonds() {
  const router = useRouter();
  const [investment, setInvestment] = useState(10000);

  const calculateReturns = () => {
    const annualReturn = 0.42; // 42% estimated annual return
    const year5 = investment * Math.pow(1 + annualReturn, 5);
    const year10 = investment * Math.pow(1 + annualReturn, 10);
    const year20 = investment * Math.pow(1 + annualReturn, 20);
    return { year5, year10, year20 };
  };

  const returns = calculateReturns();

  return (
    <div className="min-h-screen bg-gradient-to-b from-black via-yellow-950/20 to-black text-white">
      <div className="max-w-6xl mx-auto px-4 py-20">
        {/* Header */}
        <div className="text-center mb-16">
          <div className="text-6xl mb-6">💎</div>
          <h1 className="text-6xl md:text-7xl font-bold mb-6 text-yellow-500">
            VICTORY Bonds
          </h1>
          <p className="text-2xl text-gray-300 max-w-3xl mx-auto">
            The best investment in human history: Get rich while saving lives
          </p>
        </div>

        {/* The Pitch */}
        <div className="bg-gradient-to-br from-yellow-950/30 to-orange-950/30 border-2 border-yellow-700 rounded-2xl p-8 mb-12">
          <h2 className="text-3xl font-bold mb-6">The Deal</h2>
          <div className="space-y-4 text-lg">
            <p className="text-gray-300">
              VICTORY bonds give you <span className="text-yellow-400 font-bold">10% of the perpetual peace and health dividend</span> generated by the 1% Treaty.
            </p>
            <p className="text-gray-300">
              As the DIH funds trials that cure diseases, economies become more productive. That productivity gain is captured and distributed to bondholders.
            </p>
            <p className="text-yellow-400 font-bold text-xl">
              Estimated annual returns: 40-50% (compounding perpetually)
            </p>
          </div>
        </div>

        {/* Calculator */}
        <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-8 mb-12">
          <h2 className="text-3xl font-bold mb-6">Returns Calculator</h2>

          <div className="mb-8">
            <label className="block text-sm font-medium mb-3 text-gray-400">
              Your Investment Amount (USD)
            </label>
            <div className="flex items-center gap-4">
              <input
                type="range"
                min="1000"
                max="1000000"
                step="1000"
                value={investment}
                onChange={(e) => setInvestment(Number(e.target.value))}
                className="flex-1 h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer"
              />
              <div className="text-2xl font-bold text-yellow-400 min-w-[150px] text-right">
                ${investment.toLocaleString()}
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-gradient-to-br from-yellow-950/30 to-orange-950/30 border border-yellow-800 rounded-xl p-6">
              <div className="text-gray-400 text-sm mb-2">Year 5</div>
              <div className="text-3xl font-bold text-yellow-400 mb-1">
                ${returns.year5.toLocaleString(undefined, { maximumFractionDigits: 0 })}
              </div>
              <div className="text-green-500 text-sm">
                +{((returns.year5 / investment - 1) * 100).toFixed(0)}% total return
              </div>
            </div>
            <div className="bg-gradient-to-br from-yellow-950/30 to-orange-950/30 border border-yellow-700 rounded-xl p-6">
              <div className="text-gray-400 text-sm mb-2">Year 10</div>
              <div className="text-3xl font-bold text-yellow-400 mb-1">
                ${returns.year10.toLocaleString(undefined, { maximumFractionDigits: 0 })}
              </div>
              <div className="text-green-500 text-sm">
                +{((returns.year10 / investment - 1) * 100).toFixed(0)}% total return
              </div>
            </div>
            <div className="bg-gradient-to-br from-yellow-950/30 to-orange-950/30 border border-yellow-600 rounded-xl p-6">
              <div className="text-gray-400 text-sm mb-2">Year 20</div>
              <div className="text-3xl font-bold text-yellow-400 mb-1">
                ${returns.year20.toLocaleString(undefined, { maximumFractionDigits: 0 })}
              </div>
              <div className="text-green-500 text-sm">
                +{((returns.year20 / investment - 1) * 100).toFixed(0)}% total return
              </div>
            </div>
          </div>

          <div className="mt-6 text-sm text-gray-500 text-center">
            * Assumes 42% annual compounding based on health dividend projections
          </div>
        </div>

        {/* How It Works */}
        <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-8 mb-12">
          <h2 className="text-3xl font-bold mb-6">How It Works</h2>
          <div className="space-y-6">
            <div className="flex items-start gap-4">
              <div className="text-4xl">1️⃣</div>
              <div>
                <div className="font-bold text-xl mb-2">Treaty Generates Dividend</div>
                <div className="text-gray-400">
                  The 1% Treaty redirects $82B/year to medical research. This cures diseases, making populations healthier and economies more productive.
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <div className="text-4xl">2️⃣</div>
              <div>
                <div className="font-bold text-xl mb-2">Productivity Gains Captured</div>
                <div className="text-gray-400">
                  Healthier workers = higher GDP. Estimated health dividend: <span className="text-yellow-400 font-bold">$2.1 trillion/year</span> by 2038.
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <div className="text-4xl">3️⃣</div>
              <div>
                <div className="font-bold text-xl mb-2">Bondholders Receive 10%</div>
                <div className="text-gray-400">
                  VICTORY bondholders get 10% of the dividend, distributed proportionally. As the dividend grows, your returns compound.
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <div className="text-4xl">4️⃣</div>
              <div>
                <div className="font-bold text-xl mb-2">Perpetual Returns</div>
                <div className="text-gray-400">
                  The treaty is permanent. The dividend compounds forever. This isn't a get-rich-quick scheme — it's get-rich-slow and <span className="text-yellow-400 font-bold">stay rich forever</span>.
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Comparison */}
        <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-8 mb-12">
          <h2 className="text-3xl font-bold mb-6">Why This Beats Every Other Investment</h2>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-700">
                  <th className="text-left py-3 px-4">Investment</th>
                  <th className="text-right py-3 px-4">Annual Return</th>
                  <th className="text-right py-3 px-4">Risk</th>
                  <th className="text-left py-3 px-4">Outcome</th>
                </tr>
              </thead>
              <tbody className="text-gray-300">
                <tr className="border-b border-gray-800">
                  <td className="py-3 px-4">S&P 500</td>
                  <td className="text-right py-3 px-4 text-gray-400">~10%</td>
                  <td className="text-right py-3 px-4 text-yellow-600">Medium</td>
                  <td className="py-3 px-4 text-sm text-gray-500">Solid, but slow</td>
                </tr>
                <tr className="border-b border-gray-800">
                  <td className="py-3 px-4">Real Estate</td>
                  <td className="text-right py-3 px-4 text-gray-400">~8%</td>
                  <td className="text-right py-3 px-4 text-yellow-600">Medium</td>
                  <td className="py-3 px-4 text-sm text-gray-500">Illiquid, management intensive</td>
                </tr>
                <tr className="border-b border-gray-800">
                  <td className="py-3 px-4">Crypto</td>
                  <td className="text-right py-3 px-4 text-gray-400">±200%</td>
                  <td className="text-right py-3 px-4 text-red-600">Extreme</td>
                  <td className="py-3 px-4 text-sm text-gray-500">Volatile, zero-sum game</td>
                </tr>
                <tr className="border-b border-gray-800">
                  <td className="py-3 px-4 font-bold text-yellow-400">VICTORY Bonds</td>
                  <td className="text-right py-3 px-4 text-green-400 font-bold">~42%</td>
                  <td className="text-right py-3 px-4 text-green-600">Low</td>
                  <td className="py-3 px-4 text-sm text-green-400 font-bold">Saves lives + perpetual returns</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* Risk Disclosure */}
        <div className="bg-red-950/20 border border-red-900 rounded-2xl p-6 mb-12">
          <h3 className="font-bold mb-3">⚠️ Risk Disclosure</h3>
          <div className="text-sm text-gray-400 space-y-2">
            <p>
              VICTORY bonds are contingent on the 1% Treaty passing the global referendum (280M votes required).
            </p>
            <p>
              Returns are estimated based on health dividend projections. Actual returns may vary.
            </p>
            <p>
              Bonds are perpetual but may be subject to regulatory changes in participating nations.
            </p>
            <p className="text-yellow-500 font-bold">
              That said: This is the safest bet on humanity's future ever created.
            </p>
          </div>
        </div>

        {/* CTA */}
        <div className="text-center space-y-4">
          <button
            onClick={() => router.push('/join')}
            className="block w-full max-w-md mx-auto px-12 py-6 bg-yellow-600 hover:bg-yellow-700 text-black font-bold rounded-2xl text-2xl transition-all transform hover:scale-105"
          >
            💎 Reserve Your VICTORY Bonds
          </button>
          <p className="text-gray-500 text-sm">
            Join the referendum to get priority allocation when bonds launch
          </p>
          <button
            onClick={() => router.push('/')}
            className="block w-full max-w-md mx-auto px-8 py-3 bg-gray-800 hover:bg-gray-700 text-white rounded-xl transition-all"
          >
            ← Back to Home
          </button>
        </div>
      </div>
    </div>
  );
}
