"""
Auto-generated ComputeContext type for Parameter compute lambdas.

This file is generated by scripts/generate-compute-context.py
DO NOT EDIT MANUALLY - changes will be overwritten.

Usage:
    from dih_models.compute_context import ComputeContext, ComputeFunc
    
    # In Parameter definitions:
    compute: ComputeFunc = lambda ctx: ctx["PARAM_A"] + ctx["PARAM_B"]
"""

from typing import Callable, Union

# ComputeContext is a dict mapping parameter names to their numeric values
# Using a simple type alias instead of TypedDict to avoid listing 300+ keys
# This gives us basic type safety while remaining maintainable
ComputeContext = dict[str, Union[int, float]]

# Type alias for compute functions
ComputeFunc = Callable[[ComputeContext], float]
