#!/usr/bin/env python3
"""
Footer Generator
================

Generates a single shared footer HTML file used by all Quarto sites.
Reads social/action links from _quarto-shared-defaults.yml and paper
listings from all _quarto-*.yml configs.

PDF download links are NOT included here (already in each site's
page-footer YAML section).

Usage:
    from dih_models.footer_generator import generate_footer_html
    generate_footer_html(project_root)

Output:
    assets/html/generated-footer.html
"""

import logging
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

from dih_models.yaml_utils import load_quarto_config

logger = logging.getLogger("dih.footer")


def extract_footer_info(config_path: Path, config_name: str) -> Optional[Dict[str, Any]]:
    """Extract footer-relevant info from a Quarto config file."""
    config = load_quarto_config(config_path)
    if not config:
        return None
    if config_name in ("test", "manual"):
        return None

    title = None
    description = None
    site_url = None

    if "book" in config:
        book = config["book"]
        title = book.get("title")
        description = book.get("description") or book.get("abstract")
        site_url = book.get("site-url")
    elif "website" in config:
        website = config["website"]
        title = website.get("title")
        description = website.get("description")
        site_url = website.get("site-url")

    if not title or not site_url:
        return None

    emoji = config.get("dih-render", {}).get("emoji", "")

    if description:
        description = description.replace('"', '&quot;')
        if len(description) > 200:
            description = description[:197] + "..."

    return {
        "id": config_name,
        "title": title,
        "description": description,
        "emoji": emoji,
        "site_url": site_url,
    }


def _build_social_links_html(project_root: Path) -> str:
    """Read links from _quarto-shared-defaults.yml and build vote + social HTML rows."""
    shared_config = load_quarto_config(project_root / "_quarto-shared-defaults.yml")
    links = shared_config.get("links", {})

    # Vote / CTA row
    action_links = links.get("action", [])
    vote_html = ""
    if action_links:
        vote = action_links[0]
        vote_html = f"""  <p style="margin: 0.5rem 0; font-size: 0.85rem;">
    <a href="{vote['url']}" style="color: #8b7355;">Join the War on Disease</a>
  </p>"""

    # Social links row
    follow_links = links.get("follow", [])
    parts = []
    for link in follow_links:
        label = link.get("footer-label", link["label"])
        url = link["url"]
        subtitle = link.get("subtitle", link["label"])
        parts.append(f'<a href="{url}" style="color: #8b7355;" title="{subtitle}">{label}</a>')

    social_links_html = ""
    if parts:
        separator = " &nbsp;|&nbsp;\n    "
        social_links_html = f"""  <p style="margin: 0.5rem 0; font-size: 0.9rem;">
    {separator.join(parts)}
  </p>"""

    return vote_html + "\n" + social_links_html if (vote_html or social_links_html) else ""


def generate_footer_html(project_root: Path) -> Path:
    """
    Generate assets/html/generated-footer.html shared by all sites.

    Returns:
        Path to the generated file
    """
    quarto_configs = sorted(project_root.glob("_quarto-*.yml"), key=lambda p: p.name)
    papers: List[Dict[str, Any]] = []

    for config_path in quarto_configs:
        match = re.match(r"_quarto-(.+)\.yml", config_path.name)
        if not match:
            continue
        config_name = match.group(1)
        try:
            paper_info = extract_footer_info(config_path, config_name)
            if paper_info:
                papers.append(paper_info)
        except Exception as e:
            logger.warning("Failed to parse %s: %s", config_path.name, e)

    # Sort: priority papers first, then alphabetical
    priority_order = ["1-pct-treaty-impact", "iab", "wishocracy", "optimocracy", "dfda-impact", "dfda-spec"]

    def sort_key(p: Dict[str, Any]) -> tuple:
        try:
            idx = priority_order.index(p["id"])
        except ValueError:
            idx = len(priority_order)
        return (idx, p["title"])

    papers.sort(key=sort_key)

    # Build paper links
    paper_links = []
    for paper in papers:
        display = f"{paper['emoji']} {paper['title']}" if paper.get("emoji") else paper["title"]
        desc = paper.get("description", "")
        if desc:
            paper_links.append(f'<a href="{paper["site_url"]}" title="{desc}" style="color: #8b7355;">{display}</a>')
        else:
            paper_links.append(f'<a href="{paper["site_url"]}" style="color: #8b7355;">{display}</a>')

    links_html = "<br>\n    ".join(paper_links)
    social_html = _build_social_links_html(project_root)

    html_content = f"""<!-- AUTO-GENERATED: Shared Footer Content -->
<!-- Generated by dih_models/footer_generator.py -->
<!-- Do not edit manually - regenerate with generate-everything script -->
<div style="text-align: center; padding: 1rem; border-top: 1px solid #d4c5b9; margin-top: 3rem; color: #8b7355; font-size: 0.9rem;">
  <p style="margin: 0.5rem 0;">
    &copy; 2025 <a href="https://acceleratedmedicine.org" style="color: #8b7355;">The Institute for Accelerated Medicine</a> |
    <a href="https://creativecommons.org/licenses/by-nc/4.0/" style="color: #8b7355;">CC BY-NC 4.0</a> |
    <a href="https://github.com/mikepsinn/disease-eradication-plan" style="color: #8b7355;">&#128194; Source Code &amp; Data</a>
  </p>
{social_html}
  <p style="margin: 0.5rem 0; font-size: 0.85rem; border-top: 1px solid #d4c5b9; padding-top: 0.5rem; margin-top: 0.5rem;">
    <strong>Related Papers:</strong><br>
    {links_html}
  </p>
</div>
"""

    html_dir = project_root / "assets" / "html"
    html_dir.mkdir(parents=True, exist_ok=True)
    output_path = html_dir / "generated-footer.html"

    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(html_content)

    # Clean up any per-site footer files from previous runs
    for old_file in html_dir.glob("generated-footer-*.html"):
        old_file.unlink()
        logger.debug("Removed old per-site footer: %s", old_file.name)

    logger.debug("Generated %s with %d paper links", output_path.relative_to(project_root), len(papers))
    return output_path


def main():
    """CLI entry point."""
    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]

    project_root = Path(__file__).parent.parent.absolute()

    logger.debug("Generating footer HTML...")
    output_path = generate_footer_html(project_root)
    logger.debug("Output: %s", output_path)


if __name__ == "__main__":
    main()
