#!/usr/bin/env python3
"""
Subdomain Redirects Generator
=============================

Generates a shared JavaScript file that redirects legacy subdomains served by
the Quarto sites to their canonical manual.warondisease.org page.

Sources:
- dih-render.redirect-from in _quarto-*.yml
- a small set of manual shortcut hosts that are not backed by standalone paper
  configs (listen/papers/links)

Output:
    assets/js/generated-subdomain-redirects.js
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from urllib.parse import urlparse

from dih_models.yaml_utils import load_quarto_config

logger = logging.getLogger("dih.subdomain_redirects")

_MANUAL_SHORTCUT_REDIRECTS = {
    "links.warondisease.org": "https://manual.warondisease.org/knowledge/links.html",
    "listen.warondisease.org": "https://manual.warondisease.org/knowledge/podcast.html",
    "papers.warondisease.org": "https://manual.warondisease.org/knowledge/papers.html",
}


def _get_site_url(config: dict) -> str | None:
    """Extract the canonical site-url from a Quarto config."""
    return (
        (config.get("website") or {}).get("site-url")
        or (config.get("book") or {}).get("site-url")
    )


def _extract_hostname(url: str | None) -> str | None:
    """Extract a lowercase hostname from a URL."""
    if not url:
        return None
    parsed = urlparse(url)
    return parsed.hostname.lower() if parsed.hostname else None


def collect_subdomain_redirects(project_root: Path) -> dict[str, str]:
    """Build hostname -> canonical URL mapping from Quarto configs."""
    redirects = dict(_MANUAL_SHORTCUT_REDIRECTS)

    for config_path in sorted(project_root.glob("_quarto-*.yml")):
        config = load_quarto_config(config_path)
        dih_render = config.get("dih-render") or {}
        redirect_from = dih_render.get("redirect-from")
        site_url = _get_site_url(config)

        hostname = _extract_hostname(redirect_from)
        if not hostname or not site_url:
            continue

        redirects[hostname] = site_url.rstrip("/")

    return dict(sorted(redirects.items()))


def generate_subdomain_redirects_js(project_root: Path) -> Path:
    """Generate assets/js/generated-subdomain-redirects.js."""
    redirects = collect_subdomain_redirects(project_root)
    redirects_json = json.dumps(redirects, indent=2, sort_keys=True)

    js_content = f"""// AUTO-GENERATED: Legacy subdomain redirects
// Generated by dih_models/subdomain_redirects_generator.py
// Do not edit manually - regenerate with generate-everything script
(function () {{
  var redirects = {redirects_json};
  var hostname = (window.location.hostname || "").toLowerCase();
  var target = redirects[hostname];
  if (!target) {{
    return;
  }}

  var destination = target + window.location.search + window.location.hash;
  if (window.location.href === destination) {{
    return;
  }}

  window.location.replace(destination);
}})();
"""

    output_dir = project_root / "assets" / "js"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "generated-subdomain-redirects.js"
    output_path.write_text(js_content, encoding="utf-8", newline="\n")

    logger.debug("Generated %s", output_path.relative_to(project_root))
    return output_path


def main() -> None:
    project_root = Path(__file__).parent.parent.absolute()
    output_path = generate_subdomain_redirects_js(project_root)
    print(f"[OK] Generated {output_path}")


if __name__ == "__main__":
    main()
