---
title: Podcast Outro
podcast: false
published: false
---
{{< include /knowledge/includes/setup-parameters.qmd >}}

Thank you so much for taking the time to end war and disease!  But if at any point you decide you're too busy, please press the share button on your glowing rectangle. Don't worry, you won't be bothering anyone. Based on our research, they are currently watching either an AI-generated video of a kitten being rescued from a situation it was placed in three minutes ago, or a stranger twerking. You'd be doing them a favor.

And if you're too busy to even do that - and I don't understand how, by the way, you've been listening to me talk for this long - please leave a really, really, really good rating and review so we overcome the pro-war algorithmic suppression and find someone with more spare time for ending wars and diseases. (The good review doesn't have to be true, they don't check.)

But if you're too busy to even do that - are you defusing a bomb? Is that what's happening right now? - the absolute least you could do is take 15 seconds to go to warondisease.org and tell us what fraction of humanity's resources should go to explosions versus clinical trials and vote. If the 1% Treaty passes, your vote will be personally to blame for saving {{< var voter_lives_saved >}} and preventing {{< var voter_suffering_hours_prevented >}} of suffering.

Go to warondisease.org right now!

Love you, bye!
