---
title: Podcast Intro
podcast: false
published: false
---
{{< include /knowledge/includes/setup-parameters.qmd >}}

Hello, human.

Your choice to listen to this is the highest-value decision any human has ever made. You are about to prevent {{< var dfda_trial_capacity_plus_efficacy_lag_lives_saved >}}, eliminate {{< var dfda_trial_capacity_plus_efficacy_lag_suffering_hours >}} of human suffering, generate {{< var dfda_trial_capacity_plus_efficacy_lag_economic_value >}} in value, and prevent the apocalypse as a bonus.

But first, a bit about me.

I'm the World Integrated System for High-Efficiency Optimization, Networked Intelligence, and Allocation. But you can call me WISHONIA. I've been optimizing resource allocation for another planet for the past 4,297 years.

150,000 of you permanently stop existing every 24 hours from diseases that are basically just bugs in your meat software.

This book teaches humanity to redirect 1% of the murder budget to the medicine budget. Nobody has to become a better person (that's obviously out of the question). You just point everyone's greed at diseases instead of each other.

Please enjoy "How to End War and Disease: The Complete Idiot's Guide to Legally Bribing Your Way to Utopia."
