#!/usr/bin/env node
/**
 * Bulk find-and-replace across multiple file types in the project
 * 
 * Usage:
 *   npx tsx scripts/find-and-replace.ts "search" "replace" [options]
 *   npx tsx scripts/find-and-replace.ts --pairs pairs.json [options]
 * 
 * Options:
 *   --dry-run              Show what would be changed without making changes
 *   --extensions .ext,...  File extensions to search (default: .qmd,.md,.py,.yml,.yaml,.ts,.js)
 *   --path <path>          Base path to search (default: project root)
 *   --include-generated    Include auto-generated files (default: exclude)
 *   --pairs <file>         JSON file with array of [search, replace] pairs
 *   --regex                Treat search pattern as regex
 * 
 * Examples:
 *   # Simple replacement
 *   npx tsx scripts/find-and-replace.ts "old-text" "new-text"
 * 
 *   # Multiple file types
 *   npx tsx scripts/find-and-replace.ts "old-text" "new-text" --extensions .qmd,.md
 * 
 *   # Dry run to preview changes
 *   npx tsx scripts/find-and-replace.ts "old-text" "new-text" --dry-run
 * 
 *   # From JSON file with multiple pairs
 *   npx tsx scripts/find-and-replace.ts --pairs replacements.json
 * 
 *   # Regex replacement
 *   npx tsx scripts/find-and-replace.ts "image-(\d+)\.png" "figure-$1.jpg" --regex
 */

import * as fs from 'fs/promises';
import { bulkReplaceInFiles } from './lib/file-utils';

interface Args {
  search?: string;
  replace?: string;
  dryRun: boolean;
  extensions: string[];
  basePath: string;
  includeGenerated: boolean;
  pairsFile?: string;
  useRegex: boolean;
}

function parseArgs(): Args {
  const args = process.argv.slice(2);
  
  const parsed: Args = {
    dryRun: false,
    extensions: ['.qmd', '.md', '.py', '.yml', '.yaml', '.ts', '.js'],
    basePath: '',
    includeGenerated: false,
    useRegex: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    
    switch (arg) {
      case '--dry-run':
        parsed.dryRun = true;
        break;
      case '--regex':
        parsed.useRegex = true;
        break;
      case '--include-generated':
        parsed.includeGenerated = true;
        break;
      case '--extensions':
        if (i + 1 < args.length) {
          parsed.extensions = args[++i].split(',').map(ext => 
            ext.startsWith('.') ? ext : `.${ext}`
          );
        }
        break;
      case '--path':
        if (i + 1 < args.length) {
          parsed.basePath = args[++i];
        }
        break;
      case '--pairs':
        if (i + 1 < args.length) {
          parsed.pairsFile = args[++i];
        }
        break;
      default:
        if (!arg.startsWith('--')) {
          if (!parsed.search) {
            parsed.search = arg;
          } else if (!parsed.replace) {
            parsed.replace = arg;
          }
        }
        break;
    }
  }

  return parsed;
}

async function main() {
  const args = parseArgs();

  // Build replacement map
  const replacements = new Map<string | RegExp, string>();

  if (args.pairsFile) {
    // Load from JSON file
    console.log(`Loading replacement pairs from ${args.pairsFile}...`);
    const jsonContent = await fs.readFile(args.pairsFile, 'utf-8');
    const pairs: Array<[string, string]> = JSON.parse(jsonContent);
    
    for (const [search, replace] of pairs) {
      replacements.set(search, replace);
    }
    
    console.log(`Loaded ${pairs.length} replacement pairs`);
  } else if (args.search && args.replace) {
    // Single pair from command line
    const searchPattern = args.useRegex 
      ? new RegExp(args.search, 'g')
      : args.search;
    replacements.set(searchPattern, args.replace);
  } else {
    console.error('Error: Must provide either search/replace arguments or --pairs file');
    console.error('\nUsage:');
    console.error('  npx tsx scripts/find-and-replace.ts "search" "replace" [options]');
    console.error('  npx tsx scripts/find-and-replace.ts --pairs pairs.json [options]');
    process.exit(1);
  }

  console.log('\n' + '='.repeat(80));
  console.log('BULK FIND AND REPLACE');
  console.log('='.repeat(80));
  console.log(`Mode: ${args.dryRun ? 'DRY RUN (preview only)' : 'LIVE (making changes)'}`);
  console.log(`File types: ${args.extensions.join(', ')}`);
  console.log(`Base path: ${args.basePath || 'project root'}`);
  console.log(`Include auto-generated: ${args.includeGenerated ? 'yes' : 'no'}`);
  console.log(`Replacements: ${replacements.size} pair(s)`);
  
  // Show replacement pairs
  console.log('\nReplacement pairs:');
  for (const [search, replace] of replacements.entries()) {
    const searchStr = search instanceof RegExp ? search.source : search;
    console.log(`  "${searchStr}" -> "${replace}"`);
  }

  console.log('\nSearching files...\n');

  const result = await bulkReplaceInFiles(replacements, {
    extensions: args.extensions,
    basePath: args.basePath,
    dryRun: args.dryRun,
    excludeAutoGenerated: !args.includeGenerated,
  });

  console.log('='.repeat(80));
  console.log('RESULTS');
  console.log('='.repeat(80));
  console.log(`Files scanned: ${result.totalFiles}`);
  console.log(`Files changed: ${result.filesChanged}`);
  console.log(`Total changes: ${result.totalChanges}`);

  if (result.filesChanged > 0) {
    console.log('\nFiles with changes:');
    for (const detail of result.details) {
      console.log(`  ${detail.file} (${detail.changes} change${detail.changes > 1 ? 's' : ''})`);
    }
  }

  if (args.dryRun && result.filesChanged > 0) {
    console.log('\n' + '='.repeat(80));
    console.log('DRY RUN: No files were modified.');
    console.log('Run without --dry-run to apply changes.');
    console.log('='.repeat(80));
  }

  process.exit(0);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
