#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Cloudflare redirect Worker config from Quarto redirect-from fields.

Reads all _quarto-*.yml files in the project root. The configs are the only
place a redirect is declared: dih-render.redirect-from (one legacy URL or a
list) 301s to the config's canonical URL (website.site-url or book.site-url),
and dih-render.page-redirects 301s a legacy host to one page of that site.

Outputs:
- cloudflare/redirect-worker/redirect-map.json (host -> canonical URL map for
  the Cloudflare redirect Worker)
- cloudflare/redirect-worker/wrangler.jsonc (Worker config with one route per
  legacy host, so live hosts never invoke the Worker)

Host rules cannot live in a Pages _redirects file: Pages ignores domain-level
rules and follows every other rule even when a static file matches, so a
catch-all there redirects the whole site.
"""
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # pyright: ignore[reportAttributeAccessIssue]

import json
from pathlib import Path
from urllib.parse import urlparse

from dih_models.subdomain_redirects_generator import collect_subdomain_redirects

# Zones whose hosts get Worker routes. A route can only be created in a zone
# that exists on the Cloudflare account; add "dih.earth" here once that zone
# is on Cloudflare, otherwise the Worker deploy fails.
_ROUTE_ZONES = ("warondisease.org", "dfda.earth", "acceleratedmedicine.org")
_KNOWN_ZONES = ("warondisease.org", "dfda.earth", "dih.earth", "acceleratedmedicine.org")

_WORKER_NAME = "legacy-subdomain-redirects"


def _zone_for_host(host: str) -> str | None:
    """Return the known Cloudflare zone a host belongs to, if any."""
    for zone in _KNOWN_ZONES:
        if host == zone or host.endswith(f".{zone}"):
            return zone
    return None


def generate_cloudflare_redirects(project_root: Path | str) -> list[Path]:
    """Generate the Cloudflare redirect Worker's map and wrangler config.

    Returns the paths of the written files.
    """
    project_root = Path(project_root)
    worker_dir = project_root / "cloudflare" / "redirect-worker"
    worker_dir.mkdir(parents=True, exist_ok=True)

    redirects = collect_subdomain_redirects(project_root)

    # A redirect source that is also a redirect target would loop forever.
    target_hosts = {
        parsed.hostname.lower()
        for parsed in (urlparse(url) for url in redirects.values())
        if parsed.hostname
    }
    looping_hosts = sorted(host for host in redirects if host in target_hosts)
    if looping_hosts:
        raise ValueError(
            f"Redirect sources also appear as targets (would loop): {looping_hosts}"
        )

    map_path = worker_dir / "redirect-map.json"
    map_path.write_text(
        json.dumps(redirects, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    routes = [
        {"pattern": f"{host}/*", "zone_name": zone}
        for host in redirects
        if (zone := _zone_for_host(host)) in _ROUTE_ZONES
    ]

    config = {
        "name": _WORKER_NAME,
        "main": "worker.js",
        "compatibility_date": "2026-08-01",
        "routes": routes,
    }
    config_path = worker_dir / "wrangler.jsonc"
    config_path.write_text(
        "// AUTO-GENERATED by scripts/generate_redirects.py - do not edit.\n"
        "// Hosts come from dih-render.redirect-from in _quarto-*.yml; regenerate\n"
        "// with the generate-everything script. Deployed by the publish workflow.\n"
        + json.dumps(config, indent=2)
        + "\n",
        encoding="utf-8",
        newline="\n",
    )

    return [map_path, config_path]


if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent.parent
    for path in generate_cloudflare_redirects(project_root):
        print(f"[OK] Generated {path}")
