#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate Netlify _redirects file from Quarto config redirect-from fields.

Reads all _quarto-*.yml files in the project root. For each config that has
dih-render.redirect-from, generates 301 redirect rules from the old subdomain
to the canonical manual URL (website.site-url or book.site-url).

Preserves any manually-added lines in the existing _redirects file that fall
outside the auto-generated section.
"""
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # pyright: ignore[reportAttributeAccessIssue]

from pathlib import Path
from dih_models.yaml_utils import load_quarto_config

# Markers for the auto-generated section
_START_MARKER = "# --- BEGIN AUTO-GENERATED REDIRECTS (do not edit) ---"
_END_MARKER = "# --- END AUTO-GENERATED REDIRECTS ---"


def _get_site_url(config: dict) -> str | None:
    """Extract the canonical site-url from a Quarto config."""
    # website-type projects
    url = (config.get("website") or {}).get("site-url")
    if url:
        return url
    # book-type projects
    url = (config.get("book") or {}).get("site-url")
    return url


def _get_title(config: dict) -> str | None:
    """Extract a human-readable title for the comment line."""
    title = (config.get("website") or {}).get("title")
    if title:
        return title
    title = (config.get("book") or {}).get("title")
    return title


def generate_redirects(project_root: Path | str) -> Path:
    """Generate _redirects file from Quarto configs.

    Returns the path to the written _redirects file.
    """
    project_root = Path(project_root)
    redirects_path = project_root / "_redirects"

    # Collect redirect rules from all _quarto-*.yml configs
    configs = sorted(project_root.glob("_quarto-*.yml"))

    rules: list[str] = []
    for config_path in configs:
        config = load_quarto_config(config_path)
        dih_render = config.get("dih-render") or {}
        redirect_from = dih_render.get("redirect-from")
        if not redirect_from:
            continue

        site_url = _get_site_url(config)
        if not site_url:
            continue

        # Strip trailing slash from both URLs for consistency
        redirect_from = redirect_from.rstrip("/")
        site_url = site_url.rstrip("/")

        title = _get_title(config) or config_path.stem
        rules.append(f"# {title}")
        rules.append(f"{redirect_from}  {site_url}  301")
        rules.append(f"{redirect_from}/  {site_url}  301")
        rules.append(f"{redirect_from}/*  {site_url}  301")
        rules.append("")

    # Build the auto-generated section
    auto_lines = [
        _START_MARKER,
        "# Redirect from old subdomain sites to canonical manual URLs",
        "# Auto-generated by scripts/generate-redirects.py",
        "",
    ]
    auto_lines.extend(rules)
    auto_lines.append(_END_MARKER)
    auto_section = "\n".join(auto_lines)

    # Read existing _redirects and preserve manual lines
    manual_content = ""
    if redirects_path.exists():
        existing = redirects_path.read_text(encoding="utf-8")
        start_idx = existing.find(_START_MARKER)
        end_idx = existing.find(_END_MARKER)
        if start_idx != -1 and end_idx != -1:
            # Strip the old auto-generated section, keep everything else
            before = existing[:start_idx].rstrip("\n")
            after = existing[end_idx + len(_END_MARKER):].lstrip("\n")
            parts = [p for p in [before, after] if p.strip()]
            manual_content = "\n\n".join(parts)
        else:
            # No markers found; treat entire file as manual content
            manual_content = existing.strip()

    # Combine manual content and auto-generated section
    parts = [p for p in [manual_content, auto_section] if p.strip()]
    final = "\n\n".join(parts) + "\n"

    redirects_path.write_text(final, encoding="utf-8")
    return redirects_path


if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent.parent
    out = generate_redirects(project_root)
    print(f"[OK] Generated {out}")
