#!/usr/bin/env node

import fs from 'fs/promises';
import path from 'path';
import yaml from 'js-yaml';
import { getProjectRoot, isAutoGeneratedFile } from './lib/file-utils';

interface Args {
  dryRun: boolean;
  verbose: boolean;
  configFile: string;
}

interface RuleContext {
  filePath: string;
  relativePath: string;
  rootDir: string;
  partNames: string[];
  title?: string;
  baseName: string;
}

interface Rule {
  name: string;
  pattern: RegExp;
  plainText?: string;
  targetRelativePath?: string;
  externalHref?: string;
  homeFiles?: string[];
  topicAliases?: string[];
  replacement: (ctx: RuleContext) => string;
}

interface FileChange {
  file: string;
  changes: number;
}

interface ManualFileEntry {
  relativePath: string;
  partNames: string[];
}

const ROOT_DIR = getProjectRoot();
const KEY_TOPIC_PARTS = new Set(['System Optimization', 'Papers & Publications']);

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function parseArgs(): Args {
  const args = process.argv.slice(2);
  const parsed: Args = {
    dryRun: false,
    verbose: false,
    configFile: '_quarto-manual.yml',
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--dry-run') {
      parsed.dryRun = true;
    } else if (arg === '--verbose') {
      parsed.verbose = true;
    } else if (arg === '--config' && i + 1 < args.length) {
      parsed.configFile = args[++i];
    }
  }

  return parsed;
}

function getRelativeHref(fromFile: string, toFile: string): string {
  const relative = path.relative(path.dirname(fromFile), toFile).replace(/\\/g, '/');
  return relative || path.basename(toFile);
}

function makeLink(ctx: RuleContext, targetRelativePath: string, text: string): string {
  const targetPath = path.join(ctx.rootDir, targetRelativePath);
  const normalizedCurrent = path.resolve(ctx.filePath);
  const normalizedTarget = path.resolve(targetPath);
  if (normalizedCurrent === normalizedTarget) {
    return text;
  }
  return `[${text}](${getRelativeHref(ctx.filePath, normalizedTarget)})`;
}

function makeExternalLink(text: string, href: string): string {
  return `[${text}](${href})`;
}

function normalizeTopicKey(value: string): string {
  return value
    .toLowerCase()
    .replace(/%/g, ' pct ')
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function isInKeyTopicPart(ctx: RuleContext): boolean {
  return ctx.partNames.some(partName => KEY_TOPIC_PARTS.has(partName));
}

function matchesTopicAlias(ctx: RuleContext, alias: string): boolean {
  const normalizedAlias = normalizeTopicKey(alias);
  if (!normalizedAlias) {
    return false;
  }

  const candidates = [ctx.title, ctx.baseName]
    .filter((value): value is string => Boolean(value))
    .map(normalizeTopicKey);

  return candidates.some(candidate =>
    candidate === normalizedAlias ||
    candidate.startsWith(`${normalizedAlias} `)
  );
}

function isInferredHomeFile(ctx: RuleContext, rule: Rule): boolean {
  if (!isInKeyTopicPart(ctx)) {
    return false;
  }

  const aliases = rule.topicAliases ?? (rule.plainText ? [rule.plainText] : []);
  return aliases.some(alias => matchesTopicAlias(ctx, alias));
}

function isHomeFile(ctx: RuleContext, rule: Rule): boolean {
  if (rule.homeFiles && rule.homeFiles.length > 0) {
    const current = path.resolve(ctx.filePath);
    if (rule.homeFiles.some(homeFile => current === path.resolve(path.join(ctx.rootDir, homeFile)))) {
      return true;
    }
  }
  return isInferredHomeFile(ctx, rule);
}

function linkOrPlain(ctx: RuleContext, rule: Rule): string {
  if (!rule.plainText) {
    throw new Error(`Rule ${rule.name} is missing plainText`);
  }
  if (isHomeFile(ctx, rule)) {
    return rule.plainText;
  }
  if (rule.targetRelativePath) {
    return makeLink(ctx, rule.targetRelativePath, rule.plainText);
  }
  if (rule.externalHref) {
    return makeExternalLink(rule.plainText, rule.externalHref);
  }
  return rule.plainText;
}

function hrefMatchesRuleTarget(href: string, ctx: RuleContext, rule: Rule): boolean {
  if (rule.targetRelativePath) {
    const absoluteHref = path.resolve(path.dirname(ctx.filePath), href);
    const absoluteTarget = path.resolve(path.join(ctx.rootDir, rule.targetRelativePath));
    return absoluteHref === absoluteTarget;
  }
  if (rule.externalHref) {
    return href === rule.externalHref;
  }
  return false;
}

function canonicalizeLinkedText(text: string, rule: Rule): string {
  if (!rule.plainText) {
    return text;
  }
  const trimmed = text.trim();
  if (trimmed.toLowerCase() === `the ${rule.plainText.toLowerCase()}`) {
    return `The ${rule.plainText}`;
  }
  return rule.plainText;
}

function createLinkOrPlainReplacement(
  plainText: string,
  options: { targetRelativePath?: string; externalHref?: string; homeFiles?: string[] } = {}
): (ctx: RuleContext) => string {
  return (ctx: RuleContext) =>
    linkOrPlain(ctx, {
      name: plainText,
      pattern: /$^/,
      plainText,
      targetRelativePath: options.targetRelativePath,
      externalHref: options.externalHref,
      homeFiles: options.homeFiles,
      replacement: () => plainText,
    });
}

const RULES: Rule[] = [
  {
    name: 'Wishonian Optimal Governance Trajectory',
    pattern: /\bWishonian Optimal Governance Trajectory\b/gi,
    replacement: ctx =>
      `${makeLink(ctx, 'knowledge/futures/wishonia.qmd', 'Wishonian')} ${makeLink(ctx, 'knowledge/economics/gdp-trajectories.qmd', 'Optimal Governance Trajectory')}`,
  },
  {
    name: 'Minimum Sustainable Trajectory (1% Treaty)',
    pattern: /\bMinimum Sustainable Trajectory\s*\(1%\s*Treaty\)\b/gi,
    plainText: 'Minimum Sustainable Trajectory (1% Treaty)',
    targetRelativePath: 'knowledge/solution/1-percent-treaty.qmd',
    replacement: ctx => makeLink(ctx, 'knowledge/solution/1-percent-treaty.qmd', 'Minimum Sustainable Trajectory (1% Treaty)'),
  },
  {
    name: 'Failed-State Trajectory',
    pattern: /\bfailed-state trajectory\b/gi,
    plainText: 'Failed-State Trajectory',
    replacement: () => 'Failed-State Trajectory',
  },
  {
    name: 'Political Dysfunction Tax',
    pattern: /\bpolitical dysfunction tax\b/gi,
    plainText: 'Political Dysfunction Tax',
    targetRelativePath: 'knowledge/appendix/political-dysfunction-tax.qmd',
    homeFiles: ['knowledge/appendix/political-dysfunction-tax.qmd'],
    topicAliases: ['Political Dysfunction Tax'],
    replacement: createLinkOrPlainReplacement('Political Dysfunction Tax', {
      targetRelativePath: 'knowledge/appendix/political-dysfunction-tax.qmd',
      homeFiles: ['knowledge/appendix/political-dysfunction-tax.qmd'],
    }),
  },
  {
    name: 'Earth Optimization Prize',
    pattern: /\bearth optimization prize\b/gi,
    plainText: 'Earth Optimization Prize',
    targetRelativePath: 'knowledge/strategy/earth-optimization-prize.qmd',
    homeFiles: ['knowledge/strategy/earth-optimization-prize.qmd'],
    topicAliases: ['Earth Optimization Prize'],
    replacement: createLinkOrPlainReplacement('Earth Optimization Prize', {
      targetRelativePath: 'knowledge/strategy/earth-optimization-prize.qmd',
      homeFiles: ['knowledge/strategy/earth-optimization-prize.qmd'],
    }),
  },
  {
    name: 'Earth Optimization Plan v1',
    pattern: /\bearth optimization plan v1\b/gi,
    plainText: 'Earth Optimization Plan v1',
    targetRelativePath: 'knowledge/strategy/earth-optimization-plan-v1.qmd',
    homeFiles: ['knowledge/strategy/earth-optimization-plan-v1.qmd'],
    topicAliases: ['Earth Optimization Plan v1'],
    replacement: createLinkOrPlainReplacement('Earth Optimization Plan v1', {
      targetRelativePath: 'knowledge/strategy/earth-optimization-plan-v1.qmd',
      homeFiles: ['knowledge/strategy/earth-optimization-plan-v1.qmd'],
    }),
  },
  {
    name: 'Incentive Alignment Bonds',
    pattern: /\bincentive alignment bonds\b/gi,
    plainText: 'Incentive Alignment Bonds',
    targetRelativePath: 'knowledge/solution/incentive-alignment-bonds.qmd',
    homeFiles: [
      'knowledge/solution/incentive-alignment-bonds.qmd',
      'knowledge/appendix/incentive-alignment-bonds-paper.qmd',
    ],
    topicAliases: ['Incentive Alignment Bonds', 'IAB', 'IABs'],
    replacement: createLinkOrPlainReplacement('Incentive Alignment Bonds', {
      targetRelativePath: 'knowledge/solution/incentive-alignment-bonds.qmd',
      homeFiles: [
        'knowledge/solution/incentive-alignment-bonds.qmd',
        'knowledge/appendix/incentive-alignment-bonds-paper.qmd',
      ],
    }),
  },
  {
    name: 'Wishocracy',
    pattern: /\bwishocracy\b/gi,
    plainText: 'Wishocracy',
    targetRelativePath: 'knowledge/solution/wishocracy.qmd',
    homeFiles: [
      'knowledge/solution/wishocracy.qmd',
      'knowledge/appendix/wishocracy-paper.qmd',
    ],
    topicAliases: ['Wishocracy'],
    replacement: createLinkOrPlainReplacement('Wishocracy', {
      targetRelativePath: 'knowledge/solution/wishocracy.qmd',
      homeFiles: [
        'knowledge/solution/wishocracy.qmd',
        'knowledge/appendix/wishocracy-paper.qmd',
      ],
    }),
  },
  {
    name: 'Optimocracy',
    pattern: /\boptimocracy\b/gi,
    plainText: 'Optimocracy',
    targetRelativePath: 'knowledge/solution/optimocracy.qmd',
    homeFiles: [
      'knowledge/solution/optimocracy.qmd',
      'knowledge/appendix/optimocracy-paper.qmd',
    ],
    topicAliases: ['Optimocracy'],
    replacement: createLinkOrPlainReplacement('Optimocracy', {
      targetRelativePath: 'knowledge/solution/optimocracy.qmd',
      homeFiles: [
        'knowledge/solution/optimocracy.qmd',
        'knowledge/appendix/optimocracy-paper.qmd',
      ],
    }),
  },
  {
    name: 'Global Referendum',
    pattern: /\bglobal referendum\b/gi,
    plainText: 'Global Referendum',
    targetRelativePath: 'knowledge/strategy/global-referendum.qmd',
    homeFiles: ['knowledge/strategy/global-referendum.qmd'],
    topicAliases: ['Global Referendum'],
    replacement: createLinkOrPlainReplacement('Global Referendum', {
      targetRelativePath: 'knowledge/strategy/global-referendum.qmd',
      homeFiles: ['knowledge/strategy/global-referendum.qmd'],
    }),
  },
  {
    name: '1% Treaty',
    pattern: /\b1%\s+treaty\b/gi,
    plainText: '1% Treaty',
    targetRelativePath: 'knowledge/solution/1-percent-treaty.qmd',
    homeFiles: [
      'knowledge/solution/1-percent-treaty.qmd',
      'knowledge/economics/1-pct-treaty-impact.qmd',
    ],
    topicAliases: ['1% Treaty', '1 pct treaty', 'one percent treaty'],
    replacement: createLinkOrPlainReplacement('1% Treaty', {
      targetRelativePath: 'knowledge/solution/1-percent-treaty.qmd',
      homeFiles: [
        'knowledge/solution/1-percent-treaty.qmd',
        'knowledge/economics/1-pct-treaty-impact.qmd',
      ],
    }),
  },
  {
    name: 'Decentralized Institutes of Health',
    pattern: /\bdecentralized institutes of health\b/gi,
    plainText: 'Decentralized Institutes of Health',
    targetRelativePath: 'knowledge/solution/dih.qmd',
    homeFiles: ['knowledge/solution/dih.qmd'],
    topicAliases: ['Decentralized Institutes of Health', 'DIH'],
    replacement: createLinkOrPlainReplacement('Decentralized Institutes of Health', {
      targetRelativePath: 'knowledge/solution/dih.qmd',
      homeFiles: ['knowledge/solution/dih.qmd'],
    }),
  },
  {
    name: 'decentralized FDA',
    pattern: /\bdecentralized fda\b/gi,
    plainText: 'decentralized FDA',
    targetRelativePath: 'knowledge/solution/dfda.qmd',
    homeFiles: [
      'knowledge/solution/dfda.qmd',
      'knowledge/appendix/dfda-spec-paper.qmd',
      'knowledge/appendix/dfda-impact-paper.qmd',
    ],
    topicAliases: ['decentralized FDA', 'dFDA', 'dfda'],
    replacement: createLinkOrPlainReplacement('decentralized FDA', {
      targetRelativePath: 'knowledge/solution/dfda.qmd',
      homeFiles: [
        'knowledge/solution/dfda.qmd',
        'knowledge/appendix/dfda-spec-paper.qmd',
        'knowledge/appendix/dfda-impact-paper.qmd',
      ],
    }),
  },
  {
    name: 'US Efficiency Audit',
    pattern: /\bUS efficiency audit\b/gi,
    plainText: 'US Efficiency Audit',
    externalHref: 'https://us-efficiency-audit.warondisease.org',
    homeFiles: ['knowledge/appendix/us-efficiency-audit.qmd'],
    topicAliases: ['US Efficiency Audit'],
    replacement: createLinkOrPlainReplacement('US Efficiency Audit', {
      externalHref: 'https://us-efficiency-audit.warondisease.org',
      homeFiles: ['knowledge/appendix/us-efficiency-audit.qmd'],
    }),
  },
];

function extractManualQmdFiles(configDoc: any): ManualFileEntry[] {
  const fileParts = new Map<string, Set<string>>();

  const addFile = (relativePath: string, partName?: string) => {
    const parts = fileParts.get(relativePath) ?? new Set<string>();
    if (partName) {
      parts.add(partName);
    }
    fileParts.set(relativePath, parts);
  };

  const visit = (items: any[], currentPart?: string) => {
    if (!Array.isArray(items)) return;
    for (const item of items) {
      if (typeof item === 'string') {
        if (item.endsWith('.qmd')) addFile(item, currentPart);
        continue;
      }
      if (!item || typeof item !== 'object') continue;
      if (typeof item.href === 'string' && item.href.endsWith('.qmd')) {
        addFile(item.href, currentPart);
      }
      if (Array.isArray(item.chapters)) {
        visit(item.chapters, typeof item.part === 'string' ? item.part : currentPart);
      }
      if (Array.isArray(item.contents)) {
        visit(item.contents, currentPart);
      }
    }
  };

  visit(configDoc?.book?.chapters ?? []);
  return [...fileParts.entries()].map(([relativePath, parts]) => ({
    relativePath,
    partNames: [...parts],
  }));
}

function splitFrontmatter(content: string): { frontmatter: string; body: string } {
  const match = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/);
  if (!match) {
    return { frontmatter: '', body: content };
  }
  const frontmatter = match[0];
  const body = content.slice(frontmatter.length);
  return { frontmatter, body };
}

function shouldSkipLine(line: string): boolean {
  const trimmed = line.trim();

  if (!trimmed) return false;

  if (/^#\|/.test(trimmed)) return true;
  if (/^(fig-cap|tbl-cap|fig-alt|fig-sc|cap-location)\s*:/.test(trimmed)) return true;
  if (/^!\[/.test(trimmed)) return true;
  if (/^<[^>]+>/.test(trimmed)) return true;
  if (/^:::\s*\{/.test(trimmed)) return true;

  return false;
}

const PROTECTED_INLINE_REGEX =
  /!\[[^\]]*]\([^)]+\)|\[[^\]]*]\([^)]+\)|`[^`]*`|https?:\/\/\S+|<[^>]+>|\[@[^\]]+\]/g;

function applyRulesToSegment(segment: string, ctx: RuleContext, counters: Map<string, number>): string {
  let result = segment;
  const replacements: Array<{ token: string; value: string }> = [];
  let tokenIndex = 0;

  for (const rule of RULES) {
    result = result.replace(rule.pattern, () => {
      const token = `__DIH_STANDARDIZE_${tokenIndex++}__`;
      replacements.push({ token, value: rule.replacement(ctx) });
      counters.set(rule.name, (counters.get(rule.name) ?? 0) + 1);
      return token;
    });
  }

  for (const replacement of replacements) {
    result = result.replaceAll(replacement.token, replacement.value);
  }

  return result;
}

function transformLine(line: string, ctx: RuleContext, counters: Map<string, number>): string {
  const normalizedLine = line.replace(/(!?)\[([^\]]+)]\(([^)]+)\)/g, (match, imageMarker, text, href) => {
    if (imageMarker) {
      return match;
    }
    for (const rule of RULES) {
      if (!rule.plainText) continue;
      if (!hrefMatchesRuleTarget(href, ctx, rule)) continue;
      const canonicalText = canonicalizeLinkedText(text, rule);
      if (isHomeFile(ctx, rule)) {
        return canonicalText;
      }
      if (text.trim() !== canonicalText && text.trim().toLowerCase() === canonicalText.toLowerCase()) {
        return `[${canonicalText}](${href})`;
      }
    }
    return match;
  });

  let output = '';
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  PROTECTED_INLINE_REGEX.lastIndex = 0;
  while ((match = PROTECTED_INLINE_REGEX.exec(normalizedLine)) !== null) {
    output += applyRulesToSegment(normalizedLine.slice(lastIndex, match.index), ctx, counters);
    output += match[0];
    lastIndex = match.index + match[0].length;
  }
  output += applyRulesToSegment(normalizedLine.slice(lastIndex), ctx, counters);
  return output;
}

function transformBody(
  body: string,
  filePath: string,
  relativePath: string,
  partNames: string[],
  title?: string
): { changed: boolean; body: string; counters: Map<string, number> } {
  const counters = new Map<string, number>();
  const newline = body.includes('\r\n') ? '\r\n' : '\n';
  const lines = body.split(/\r?\n/);
  const out: string[] = [];

  let inFence = false;
  let fenceMarker = '';
  let inMathBlock = false;
  let inHtmlComment = false;

  const ctx: RuleContext = {
    filePath,
    relativePath,
    rootDir: ROOT_DIR,
    partNames,
    title,
    baseName: path.basename(filePath, path.extname(filePath)),
  };

  for (const line of lines) {
    const trimmed = line.trim();

    if (inHtmlComment) {
      out.push(line);
      if (trimmed.includes('-->')) {
        inHtmlComment = false;
      }
      continue;
    }

    if (inFence) {
      out.push(line);
      if (trimmed.startsWith(fenceMarker)) {
        inFence = false;
        fenceMarker = '';
      }
      continue;
    }

    if (inMathBlock) {
      out.push(line);
      if (trimmed === '$$') {
        inMathBlock = false;
      }
      continue;
    }

    if (trimmed.startsWith('<!--')) {
      out.push(line);
      if (!trimmed.includes('-->')) {
        inHtmlComment = true;
      }
      continue;
    }

    const fenceMatch = trimmed.match(/^(```|~~~)/);
    if (fenceMatch) {
      out.push(line);
      inFence = true;
      fenceMarker = fenceMatch[1];
      continue;
    }

    if (trimmed === '$$') {
      out.push(line);
      inMathBlock = true;
      continue;
    }

    if (shouldSkipLine(line)) {
      out.push(line);
      continue;
    }

    out.push(transformLine(line, ctx, counters));
  }

  const newBody = out.join(newline);
  return {
    changed: newBody !== body,
    body: newBody,
    counters,
  };
}

async function main() {
  const args = parseArgs();
  const configPath = path.join(ROOT_DIR, args.configFile);
  const configContent = await fs.readFile(configPath, 'utf-8');
  const configDoc = yaml.load(configContent) as any;

  const candidateFiles = extractManualQmdFiles(configDoc)
    .map(entry => ({
      ...entry,
      absolutePath: path.join(ROOT_DIR, entry.relativePath),
    }))
    .filter(entry => !isAutoGeneratedFile(entry.absolutePath));

  const files: Array<ManualFileEntry & { absolutePath: string }> = [];
  for (const entry of candidateFiles) {
    if (await pathExists(entry.absolutePath)) {
      files.push(entry);
    } else if (args.verbose) {
      console.warn(`[skip missing] ${entry.relativePath}`);
    }
  }

  const fileChanges: FileChange[] = [];
  const totalCounters = new Map<string, number>();

  for (const file of files) {
    const original = await fs.readFile(file.absolutePath, 'utf-8');
    const { frontmatter, body } = splitFrontmatter(original);
    let title: string | undefined;
    if (frontmatter) {
      try {
        const frontmatterDoc = yaml.load(
          frontmatter.replace(/^---\r?\n/, '').replace(/\r?\n---\r?\n?$/, '')
        ) as any;
        if (frontmatterDoc && typeof frontmatterDoc.title === 'string') {
          title = frontmatterDoc.title;
        }
      } catch {
        // Ignore frontmatter parse failures and fall back to basename matching.
      }
    }
    const transformed = transformBody(body, file.absolutePath, file.relativePath, file.partNames, title);

    if (!transformed.changed) {
      continue;
    }

    if (!args.dryRun) {
      await fs.writeFile(file.absolutePath, frontmatter + transformed.body, 'utf-8');
    }

    let fileCount = 0;
    for (const [ruleName, count] of transformed.counters.entries()) {
      if (count > 0) {
        totalCounters.set(ruleName, (totalCounters.get(ruleName) ?? 0) + count);
        fileCount += count;
      }
    }

    fileChanges.push({
      file: file.relativePath,
      changes: fileCount,
    });

    if (args.verbose) {
      console.log(`${args.dryRun ? '[dry-run] ' : ''}${file.relativePath} (${fileCount} changes)`);
    }
  }

  console.log(`Scanned ${files.length} manual QMD files.`);
  console.log(`${args.dryRun ? 'Would change' : 'Changed'} ${fileChanges.length} files.`);

  if (fileChanges.length > 0) {
    console.log('\nFiles:');
    for (const detail of fileChanges) {
      console.log(`  ${detail.file} (${detail.changes})`);
    }

    console.log('\nRule counts:');
    for (const [ruleName, count] of [...totalCounters.entries()].sort((a, b) => b[1] - a[1])) {
      console.log(`  ${ruleName}: ${count}`);
    }
  }
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
